### ISSUE TITLE
Implement sizeThatFits

### ISSUE THREAD

**Issue by JonasGessner** [me-abhinav/NumberMorphView#2]
The Readme says: "Preferred aspect ratio of the view is 13 : 24"

Instead of handing over the task of making sure the aspect ratio is always (which most people will probably fail), it would be much easier to implement the `siteThatFits:` method and return a correct size for the view.

It would be awesome if you could implement this! I would do it myself, it should just be a few lines, but I'm too busy :S (bad excuse).

**Comment by me-abhinav** [comment]
@JonasGessner great idea. I will definitely implement this.

**Comment by MosheBerman** [comment]
Where does 13:24 come from anyway?

**Comment by me-abhinav** [comment]
@MosheBerman when I was designing my font, I used a canvas which had an aspect ratio of 13:24.
No particular reason for choosing this size.

**Comment by meabhinav** [comment]
Implemented sizeThatFits. Right now I'm ignoring the provided size and returning the intrinsic size which is computer based on the font size.

**Comment by me-abhinav** [comment]
Implemented sizeThatFits. Right now I'm ignoring the provided size and returning the intrinsic size which is computed based on the font size.
