### ISSUE TITLE
Ticker Animation?

### ISSUE THREAD

**Issue by AndrewSB** [me-abhinav/NumberMorphView#4]
Thank you for building this!!

Would be really awesome to see some sort of ticker animation? Like what Robinhood has. I could see that being used by a lot of people :)

**Comment by me-abhinav** [comment]
Hi @AndrewSB!
Can you give an example of which animation are you talking about? Are you talking about horizontally sliding text? I'm not aware of robinhood.

**Comment by AndrewSB** [comment]
![robinhood gif](https://j.gifs.com/g5347l.gif)
