### ISSUE TITLE
Swift3

### ISSUE THREAD

**Issue by alapergola** [me-abhinav/NumberMorphView#6]
Any plan for a Swift3 migration ?

Tried with Xcode8 --> Convert syntax to Swift 3 and works like magic.
It will be a matter of uploading new code.

**Comment by me-abhinav** [comment]
Is it possible for you to raise a PR? I will be happy to merge. :)

**Comment by paperboy1109** [comment]
I can confirm @alapergola 's finding. In Xcode 8.0 the conversion tool that automatically opens seems to succeed in migrating the code into Swift 3.0.  I tried this in a working project of my own, and also cloned the repository and opened it in Xcode on my machine.  I had no problems building and running.

Would it be helpful for me to make a pull request on the cloned repository?  Thanks for your great work.

**Comment by me-abhinav** [comment]
@paperboy1109 Yes it will be very helpful if someone raise a pull request or I will have to do it myself this weekend. I have been a little busy these days.
