### ISSUE TITLE
Pod not getting from Swift 3 code

### ISSUE THREAD

**Issue by gmogames** [me-abhinav/NumberMorphView#9]
Hi There,

Apparently even after the latest PR to include support for swift 3, the podspec still grabbing the code from the 0.1.1 tag, which has not been updated with this new code.

So using Cocoapods still get the code for Swift 2.2.

I think you need to get a new tag in place and update the spec, or just make the spec point to master, since Dev is not in sync with it as well.

Thanks!

**Comment by me-abhinav** [comment]
Pushed trunk. Please use:
`pod 'NumberMorphView', '0.2.0'`
